name: alpha
description: A Flutter project for alpha swim academy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0


  shared_preferences: ^2.0.15
  # Import the provider package.
  provider: ^6.0.4
  persian_datetime_picker: ^3.1.0
  image_picker: ^1.1.2
  device_info_plus: ^11.5.0
  mockito: ^5.3.2
  package_info_plus: ^8.3.0
  http: ^1.0.0
  lint: ^2.1.2
  rxdart: ^0.28.0
  carousel_slider: ^5.1.1
  multiselect: ^0.1.1
  webview_flutter: ^4.2.2
  fl_chart: ^1.0.0
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.14.4
  photo_view: ^0.15.0
  visibility_detector: ^0.4.0+2
  lottie: ^3.3.1
  uuid: ^4.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  freezed_annotation:
  freezed:

  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9

dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter
  #import test package
  lints: ^5.1.1
  test:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: AlphaFonts
      fonts:
        - asset: assets/fonts/vazir_bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/vazir_regular.ttf
          style: normal
          weight: 400



  assets:
    - assets/jik.json
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/images/im_contact.png
    # To add src to your application, add an src section, like this:
    # src:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding src from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # sai:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
