// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0d40CN8Zj2bV-sI1Ih8nc-aMSuIuakgI',
    appId: '1:712447123916:android:c488f806aa9551c601bd69',
    messagingSenderId: '712447123916',
    projectId: 'alphaswim-90b68',
    authDomain: 'alphaswim-90b68.firebaseapp.com',
    storageBucket: 'alphaswim-90b68.appspot.com',

  );
  //
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyBuT2Wic5MXuCaXIhSI5j73rEwus0wnerU',
  //   appId: '1:542971807667:android:f8dc3e932c67135690adc6',
  //   messagingSenderId: '542971807667',
  //   projectId: 'mobile-app-user-f8a89',
  //   storageBucket: 'mobile-app-user-f8a89.appspot.com',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBa9x9nZ9OEf_3DUU1U5Wg4A4Xd8pFw2Bw',
  //   appId: '1:542971807667:ios:31ae3d7f579b728b90adc6',
  //   messagingSenderId: '542971807667',
  //   projectId: 'mobile-app-user-f8a89',
  //   storageBucket: 'mobile-app-user-f8a89.appspot.com',
  //   iosClientId: '542971807667-pv8ch46244cb1joc8l4v6omrhaurmnak.apps.googleusercontent.com',
  //   iosBundleId: 'com.sai.nona',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBa9x9nZ9OEf_3DUU1U5Wg4A4Xd8pFw2Bw',
  //   appId: '1:542971807667:ios:205b5a2655f4207990adc6',
  //   messagingSenderId: '542971807667',
  //   projectId: 'mobile-app-user-f8a89',
  //   storageBucket: 'mobile-app-user-f8a89.appspot.com',
  //   iosClientId: '542971807667-3njogbc5gviumvt8tip0kriol7mhganr.apps.googleusercontent.com',
  //   iosBundleId: 'com.sai.mobileAppUser.RunnerTests',
  // );
}
